description: ''
num_gpus: 1
local_rank: 0
use_cuda: true
is_training: true
logger_level: info
use_half_precision: false
pretrained: ''
best_model: ''
predict_offsets: true
use_exp: 0.0
debug: false
seed: 3407
cuda_id: 0
chunk_size: 21
n_epochs: 20
n_inf_sample: 10
expr_ID: fintune909
summary_folder: summaries
results_folder: results
code_folder: code
summary_steps: 20
backend: nccl
checkpoint_folder: checkpoints
checkpoint_steps: 1000
eval_steps: 500
float_dtype: float32
max_duration: .inf
max_iters: .inf
network:
  type: Coop
  use_sync_bn: true
  rnet_iter: 1
  coop_model:
    joints_num: 36
    hidden_size: 256
    head_num: 8
    dropout_rate: 0.2
    num_layers: 8
  early_stopping:
    monitor: val_loss
    min_delta: 0.0
    patience: 5
    verbose: true
    mode: min
optim:
  type: adamw
  lr: 2.0e-05
  weight_decay: 0.0001
  weight_decay_bias: 0.0
body_model:
  type: smplx
  model_path: ''
datasets:
  batch_size: 128
  use_equal_sampling: true
  use_packed: true
  use_face_contour: true
  splits: {}
  num_workers:
    train: 0
    val: 0
    test: 0
  dataset_dir: ''
  objects_dir: ''
  grab_path: ''
  fps: 30
  past_frames: 10
  future_pred: 10
  chunk_size: 21
  model_path: ''
losses:
  edge:
    type: l1
    weight: 0.0
  vertices:
    type: l1
    weight: 5.0
  vertices_consist:
    type: l1
    weight: 0.0
  rh_vertices:
    type: l1
    weight: 0.0
  feet_vertices:
    type: l1
    weight: 0.0
  pose:
    type: l2
    weight: 20.0
  vertices_hd:
    type: masked-l2
    weight: 1.0
    hd_fname: ''
  velocity:
    type: l2
    weight: 1.0
  acceleration:
    type: l2
    weight: 1.0
  contact:
    type: l1
    weight: 0.0
  dist_loss_exp: false
  dist_loss_exp_v: true
  kl_loss:
    type: l1
    weight: 0.0005
evaluation:
  body:
    v2v:
    - procrustes
